-- Refract Supabase Schema
-- Migration from SQLite to PostgreSQL

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users table
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  auth_id UUID NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  onboarding_completed BOOLEAN NOT NULL DEFAULT false,
  language TEXT NOT NULL DEFAULT 'en',
  theme TEXT NOT NULL DEFAULT 'light' CHECK (theme IN ('light', 'dark')),
  avatar_url TEXT,
  github_installation_id BIGINT,
  github_token TEXT,
  plan TEXT NOT NULL DEFAULT 'free' CHECK (plan IN ('free', 'pro', 'team', 'enterprise')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Migration: add plan column if not present
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'plan'
  ) THEN
    ALTER TABLE public.users ADD COLUMN plan TEXT NOT NULL DEFAULT 'free'
      CHECK (plan IN ('free', 'pro', 'team', 'enterprise'));
  END IF;
END $$;

-- Projects table
CREATE TABLE IF NOT EXISTS projects (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  path TEXT,
  repo TEXT,
  branch TEXT DEFAULT 'main',
  status TEXT DEFAULT 'Not analysed',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_run TIMESTAMPTZ
);

-- Health snapshots
CREATE TABLE IF NOT EXISTS health_snapshots (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  score INTEGER NOT NULL,
  issue_count INTEGER NOT NULL,
  high INTEGER NOT NULL,
  medium INTEGER NOT NULL,
  low INTEGER NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL
);

-- Project decisions
CREATE TABLE IF NOT EXISTS project_decisions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  issue_signature TEXT NOT NULL,
  category TEXT NOT NULL,
  file TEXT NOT NULL,
  problem TEXT NOT NULL,
  decision TEXT NOT NULL,
  applied INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL
);

-- Settings (global guidelines)
CREATE TABLE IF NOT EXISTS settings (
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  PRIMARY KEY (user_id, key)
);

-- Activity log
CREATE TABLE IF NOT EXISTS activity (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  project_name TEXT NOT NULL,
  type TEXT NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════════════════════════
-- Webhook events queue (Pillar 1 — Drift Monitor)
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS webhook_events (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID REFERENCES projects(id) ON DELETE SET NULL,
  installation_id BIGINT NOT NULL,
  event_type TEXT NOT NULL,                     -- 'push', 'pull_request', 'installation', 'installation_repositories'
  action TEXT,                                   -- 'opened', 'synchronize', 'reopened', 'deleted', etc.
  repo_full_name TEXT NOT NULL,                  -- 'owner/repo'
  repo_url TEXT NOT NULL,                        -- 'https://github.com/owner/repo'
  branch TEXT,
  commit_sha TEXT,
  pr_number INTEGER,
  payload JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  error TEXT,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════════════════════════
-- Analysis results (full snapshot with category breakdown)
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS analysis_results (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  snapshot_id UUID REFERENCES health_snapshots(id) ON DELETE SET NULL,
  event_id UUID REFERENCES webhook_events(id) ON DELETE SET NULL,
  commit_sha TEXT,
  branch TEXT,
  score INTEGER NOT NULL,
  issue_count INTEGER NOT NULL,
  high INTEGER NOT NULL,
  medium INTEGER NOT NULL,
  low INTEGER NOT NULL,
  issue_counts_by_category JSONB,               -- {"any-type": 5, "dead-state": 2, ...}
  file_issue_counts JSONB,                      -- {"src/foo.ts": 3, "src/bar.ts": 1, ...}
  trigger TEXT NOT NULL DEFAULT 'manual'
    CHECK (trigger IN ('manual', 'push', 'pull_request', 'cron')),
  duration_ms INTEGER,                           -- analysis execution time in ms
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════════════════════════
-- Drift alerts (generated by drift detection algorithm)
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS drift_alerts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  analysis_result_id UUID REFERENCES analysis_results(id) ON DELETE CASCADE,
  alert_type TEXT NOT NULL
    CHECK (alert_type IN ('score_drop', 'category_spike', 'anomaly', 'decay_hotspot', 'architectural_drift')),
  severity TEXT NOT NULL
    CHECK (severity IN ('info', 'warning', 'critical')),
  message TEXT NOT NULL,
  metadata JSONB,                               -- extra context (file path, category, before/after values)
  acknowledged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON public.users(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_projects_user_id ON projects(user_id);
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON projects(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_health_snapshots_project_id ON health_snapshots(project_id);
CREATE INDEX IF NOT EXISTS idx_health_snapshots_timestamp ON health_snapshots(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_decisions_project_sig ON project_decisions(project_id, issue_signature);
CREATE INDEX IF NOT EXISTS idx_activity_project_id ON activity(project_id);
CREATE INDEX IF NOT EXISTS idx_activity_created_at ON activity(created_at DESC);

-- Webhook events indexes
CREATE INDEX IF NOT EXISTS idx_webhook_events_status ON webhook_events(status);
CREATE INDEX IF NOT EXISTS idx_webhook_events_project_id ON webhook_events(project_id);
CREATE INDEX IF NOT EXISTS idx_webhook_events_created_at ON webhook_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_webhook_events_repo_url ON webhook_events(repo_url);

-- Analysis results indexes
CREATE INDEX IF NOT EXISTS idx_analysis_results_project_id ON analysis_results(project_id);
CREATE INDEX IF NOT EXISTS idx_analysis_results_created_at ON analysis_results(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analysis_results_trigger ON analysis_results(trigger);

-- Drift alerts indexes
CREATE INDEX IF NOT EXISTS idx_drift_alerts_project_id ON drift_alerts(project_id);
CREATE INDEX IF NOT EXISTS idx_drift_alerts_severity ON drift_alerts(severity);
CREATE INDEX IF NOT EXISTS idx_drift_alerts_created_at ON drift_alerts(created_at DESC);

-- Enable Row Level Security
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE health_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity ENABLE ROW LEVEL SECURITY;

-- RLS Policies for users
CREATE POLICY "Users can view own profile" ON public.users
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.users
  FOR UPDATE USING (auth.uid() = id);

-- RLS Policies for projects
CREATE POLICY "Users can view own projects" ON projects
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own projects" ON projects
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own projects" ON projects
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own projects" ON projects
  FOR DELETE USING (auth.uid() = user_id);

-- RLS Policies for health_snapshots
CREATE POLICY "Users can view own health snapshots" ON health_snapshots
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM projects WHERE projects.id = health_snapshots.project_id AND projects.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own health snapshots" ON health_snapshots
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM projects WHERE projects.id = health_snapshots.project_id AND projects.user_id = auth.uid()
    )
  );

-- RLS Policies for project_decisions
CREATE POLICY "Users can view own decisions" ON project_decisions
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM projects WHERE projects.id = project_decisions.project_id AND projects.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own decisions" ON project_decisions
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM projects WHERE projects.id = project_decisions.project_id AND projects.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own decisions" ON project_decisions
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM projects WHERE projects.id = project_decisions.project_id AND projects.user_id = auth.uid()
    )
  );

-- RLS Policies for settings
CREATE POLICY "Users can view own settings" ON settings
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can upsert own settings" ON settings
  FOR ALL USING (auth.uid() = user_id);

-- RLS Policies for activity
CREATE POLICY "Users can view own activity" ON activity
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM projects WHERE projects.id = activity.project_id AND projects.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own activity" ON activity
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM projects WHERE projects.id = activity.project_id AND projects.user_id = auth.uid()
    )
  );

-- ═══════════════════════════════════════════════════════════════════════════════
-- RLS Policies for webhook_events
-- ═══════════════════════════════════════════════════════════════════════════════

ALTER TABLE webhook_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own webhook events" ON webhook_events
  FOR SELECT USING (
    project_id IS NULL OR
    EXISTS (
      SELECT 1 FROM projects WHERE projects.id = webhook_events.project_id AND projects.user_id = auth.uid()
    )
  );

-- Service role can insert (called from webhook which is unauthenticated)
-- Anonymous inserts are allowed via service_role key only

-- ═══════════════════════════════════════════════════════════════════════════════
-- RLS Policies for analysis_results
-- ═══════════════════════════════════════════════════════════════════════════════

ALTER TABLE analysis_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own analysis results" ON analysis_results
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM projects WHERE projects.id = analysis_results.project_id AND projects.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own analysis results" ON analysis_results
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM projects WHERE projects.id = analysis_results.project_id AND projects.user_id = auth.uid()
    )
  );

-- ═══════════════════════════════════════════════════════════════════════════════
-- RLS Policies for drift_alerts
-- ═══════════════════════════════════════════════════════════════════════════════

ALTER TABLE drift_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own drift alerts" ON drift_alerts
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM projects WHERE projects.id = drift_alerts.project_id AND projects.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own drift alerts" ON drift_alerts
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM projects WHERE projects.id = drift_alerts.project_id AND projects.user_id = auth.uid()
    )
  );

-- ═══════════════════════════════════════════════════════════════════════════════
-- Migration: quality_gate_score on projects
-- ═══════════════════════════════════════════════════════════════════════════════

ALTER TABLE projects ADD COLUMN IF NOT EXISTS quality_gate_score INTEGER DEFAULT 60;

-- ═══════════════════════════════════════════════════════════════════════════════
-- audit_links — public shareable audit reports (no source code)
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS audit_links (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  slug TEXT UNIQUE NOT NULL,
  project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  project_name TEXT NOT NULL,
  score INTEGER NOT NULL,
  issue_count INTEGER NOT NULL,
  high INTEGER NOT NULL DEFAULT 0,
  medium INTEGER NOT NULL DEFAULT 0,
  low INTEGER NOT NULL DEFAULT 0,
  scanned_files INTEGER NOT NULL DEFAULT 0,
  category_counts JSONB DEFAULT '{}',
  top_issues JSONB DEFAULT '[]',
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE audit_links ENABLE ROW LEVEL SECURITY;

-- Anyone can read audit links (public share)
CREATE POLICY "public_read_audit_links" ON audit_links
  FOR SELECT USING (true);

-- Only the owner can create audit links
CREATE POLICY "owner_insert_audit_links" ON audit_links
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Owner can delete their own audit links
CREATE POLICY "owner_delete_audit_links" ON audit_links
  FOR DELETE USING (auth.uid() = user_id);
